package hw2_JdbcService;

import hw2_JdbcService.util.ConnectionManager;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {
String sql = """
       INSERT INTO info(data)
       VALUES 
       ('autogenerated')
        
               """;
        try (Connection connection = ConnectionManager.open();
             Statement statement = connection.createStatement()) {

            System.out.println(connection.getTransactionIsolation());

            int execute = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            ResultSet generatedKeys = statement.getGeneratedKeys();
            while (generatedKeys.next()) {
                int generatedId = generatedKeys.getInt("id");
                System.out.println(generatedId);
            }



        }
    }
}
